import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Cairo, Geist } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Metadata } from "next";
import "aos/dist/aos.css";
import { ToastContainer } from "react-toastify";

const cairo = Cairo({
  subsets: ["arabic"],
});
const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "صحتي",
  description: "Generated by imad - yacine",
};
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const dir = locale === "ar" ? "rtl" : "ltr";
  const font = locale === "ar" ? cairo.className : geist.className;

  return (
    <html lang={locale} dir={dir} className={font}>
      <ToastContainer />
      <NextIntlClientProvider>
        <body className="">
          <NavBar />
          <div className="mt-16">{children}</div>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
